#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cargo fmt -- --check
cargo clippy -p velocity-vaults -- -D warnings -D clippy::unwrap_used -D clippy::expect_used -D clippy::panic
cargo clippy -p velocity-vaults --tests -- -D warnings
cargo test --quiet
yarn prettify
yarn lint
cd ts/sdk
tsc